pdf/Models/FileDetail.cs
namespace pdf.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class FileDetail
    {
        public int Id { get; set; }

        [StringLength(60)]
        public string FileName { get; set; }

        public byte[] FileContent { get; set; }
    }
}

pdf/Controllers/DownloadController.cs
using pdf.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using System.Web;
using System.Web.Mvc;

namespace pdf.Controllers
{
    public class DownloadController : Controller
    {
        #region Upload Download file  
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public FileResult DownLoadFile(int id)
        {


            List<FileDetail> ObjFiles = GetFileList();

            var FileById = (from FC in ObjFiles
                            where FC.Id.Equals(id)
                            select new { FC.FileName, FC.FileContent }).ToList().FirstOrDefault();

            return File(FileById.FileContent, "application/pdf", FileById.FileName);

        }
        #endregion

        #region View Uploaded files  
        [HttpGet]
        public PartialViewResult FileDetails()
        {
            List<FileDetail> DetList = GetFileList();

            return PartialView("FileDetails", DetList);


        }
        private List<FileDetail> GetFileList()
        {
            List<FileDetail> DetList = new List<FileDetail>();

            DbConnection();
            SqlDataReader reader;

            using (con)
            {
                try
                {
                    con.Open();

                    //read annual balance
                    SqlCommand com = new SqlCommand("GetFileDetails", con);
                    com.CommandType = CommandType.StoredProcedure;
                    reader = com.ExecuteReader();
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            FileDetail evb = new FileDetail();
                            if (!(reader["Id"] is DBNull))
                                evb.Id = Convert.ToInt16(reader["Id"]);


                            if (!(reader["FileName"] is DBNull))
                                evb.FileName = Convert.ToString(reader["FileName"]);

                            if (!(reader["FileContent"] is DBNull))
                                evb.FileContent = ObjectToByteArray(reader["FileContent"]);


                            DetList.Add(evb);
                        }
                    }
                }
                catch (Exception)
                {
                    return new List<FileDetail>();
                }
            }
            return DetList;
        }

        byte[] ObjectToByteArray(object obj)
        {
            if (obj == null)
                return null;
            BinaryFormatter bf = new BinaryFormatter();
            using (MemoryStream ms = new MemoryStream())
            {
                bf.Serialize(ms, obj);
                return ms.ToArray();
            }
        }

        #endregion
        #region Database connection  

        private SqlConnection con;
        private string constr;
        private void DbConnection()
        {
            constr = ConfigurationManager.ConnectionStrings["Data"].ToString();
            con = new SqlConnection(constr);

        }
        #endregion
    }
}

pdf/Views/Download/FileDetails.cshtml
@model IEnumerable<pdf.Models.FileDetail>
<table class="table table-bordered">
    <tr>
        <th class="col-md-4">
            @Html.DisplayNameFor(model => model.FileName)
        </th>

        <th class="col-md-2"></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>

            <td>
                @*@Html.ActionLink("Downlaod", "DownLoadFile", new { id = item.Id })*@
                <button id="download">download</button>
            </td>
        </tr>
    }

</table>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $('#download').click(function (e) {
        e.preventDefault();
        alert("sdfsdfsdfdsfsd");
    });

</script>

pdf/Views/Download/Index.cshtml
@{
    ViewBag.Title = "www.compilemode.com";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 text-success">
            @ViewBag.FileStatus
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-8">
            @Html.Action("FileDetails", "Download") 
        </div>
    </div>
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>